# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pipeline-compiler-service.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fpipeline-compiler-service.proto\x12\tmyservice\"\x1e\n\x0e\x43ompileRequest\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\"m\n\x0c\x43ompileReply\x12\x30\n\nstatusCode\x18\x01 \x01(\x0e\x32\x1c.myservice.CompilationResult\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x11\n\x04\x64\x61ta\x18\x03 \x01(\x0cH\x00\x88\x01\x01\x42\x07\n\x05_data*I\n\x11\x43ompilationResult\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x06\n\x02OK\x10\x01\x12\x10\n\x0cSYNTAX_ERROR\x10\x02\x12\r\n\tEXCEPTION\x10\x03\x32\x62\n\x17PipelineCompilerService\x12G\n\x0f\x43ompilePipeline\x12\x19.myservice.CompileRequest\x1a\x17.myservice.CompileReply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pipeline_compiler_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_COMPILATIONRESULT']._serialized_start=189
  _globals['_COMPILATIONRESULT']._serialized_end=262
  _globals['_COMPILEREQUEST']._serialized_start=46
  _globals['_COMPILEREQUEST']._serialized_end=76
  _globals['_COMPILEREPLY']._serialized_start=78
  _globals['_COMPILEREPLY']._serialized_end=187
  _globals['_PIPELINECOMPILERSERVICE']._serialized_start=264
  _globals['_PIPELINECOMPILERSERVICE']._serialized_end=362
# @@protoc_insertion_point(module_scope)
